# Generated by Django 5.0.3 on 2024-04-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.AddField(
            model_name='book',
            name='no_of_pages',
            field=models.IntegerField(default=0),
        ),
    ]
